/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/components/AddAsset.jsx",
    "./src/components/Arrow.jsx",
    "./src/components/BarChart.jsx",
    "./src/components/Coins.jsx",
    "./src/components/CurrencyConverter.jsx",
    "./src/components/CurrencySelector.jsx",
    "./src/components/DeleteAsset.jsx",
    "./src/components/EditAsset.jsx",
    "./src/components/LineChart.jsx",
    "./src/components/LineChartCurrencyConverter.jsx",
    "./src/components/LineChartIndividualCoin.jsx",
    "./src/components/PortfolioItem.jsx",
    "./src/components/PurchaseAmount.jsx",
    "./src/components/PurchaseDate.jsx",
    "./src/components/ResultList.jsx",
    "./src/components/SearchInput.jsx",
    "./src/components/SlickCarousel.jsx",
    "./src/contexts/cryptoContext.jsx",
    "./src/pages/CoinPage.jsx",
    "./src/pages/Homepage.jsx",
    "./src/pages/Portfolio.jsx",
    "./src/App.jsx",
    "./src/components/CoinPagePlusInCircleIcon.jsx",
    "./src/components/DaysButton.jsx",
  ],
  theme: {
    extend: {
      textColor:{
        skin: {
          "selected-button-app-name-text": 'var(--color-text-selected-button-app-name)',
          "unselected-button-text": 'var(--color-text-unselected-button)',
          "currency-selector-text-color": 'var(--color-text-currency-selector)',
          "search-bar-place-holder-text-color": 'var(--color-text-search-bar-place-holder)',
          "coins-currency-selector-selected-button-text-color": 'var(--color-text-coins-currency-selector-selected-button)',
          "coins-currency-selector-unselected-button-text-color": 'var(--color-text-coins-currency-selector-unselected-button)',
          "carousel-selected-button-text-color": 'var(--color-text-carousel-selected-button)',
          "carousel-unselected-button-text-color": 'var(--color-text-carousel-unselected-button)',
          "carousel-current-price-text-color": 'var(--color-text-carousel-current-price)',
          "select-coin-to-view-chart-prompt-text-color": 'var(--color-text-select-coin-to-view-chart-prompt)',
          "days-button-top-bottom-fifty-text-color":'var(--color-text-days-button-top-bottom-fifty)',
          "unselected-days-top-bottom-fifty-button-text-color":'var(--color-text-unselected-days-button-top-bottom-fifty)',
          "coin-list-titles-text-color":'var(--color-text-coin-list-titles)',
          "coin-list-text-color":'var(--color-text-coin-list)'
        }
      },
      backgroundColor: {
        skin: {
          app: 'var(--color-background-app)',
          "unselected-button-bg": 'var(--color-background-unselected-button-search-bar-currency-selector)',
          "carousel-selected-button-background-color": 'var(--color-background-carousel-selected-button)',
          "carousel-unselected-button-background-color": 'var(--color-background-carousel-unselected-button)',
          "days-bar-background-color": 'var(--color-background-days-bar)',
          "days-button-background-color": 'var(--color-background-days-button)',
          "charts-background-color":'var(--color-background-charts)',
          "coin-list-background-color":'var(--color-background-coin-list)',
          "coins-converter-selected-button-background": 'var(--color-background-coins-converter-selected-button)',
          "coins-converter-unselected-button-background": 'var(--color-background-coins-converter-unselected-button)',
          "coins-converter-wrapper-background":'var(--color-background-coins-converter-wrapper)',

        }
      },
      colors: {
        "crpyto-background-dark": "#13121A",
        "button-selected": "rgba(97, 97, 214, 0.5)",
        "button-unselected-search-bar-background": "#191925",
        "button-unselected-search-bar-background-light": "rgba(204, 204, 250, 0.4)",
        "go-up": "#01F1E3",
        "go-down": "#FE2264",
        "line-bar-chart-background": "#191932",
        "right-currency-background": "#1E1932",
        "to-in-currency-converter": "rgba(209, 209, 209, 0.8)",
        "coin-icon-background": "#2C2C4A",
        "portfolio-item-price-properties": "#2D2D51",
        "portfolio-item-bar": "#01F1E3",
        "portfolio-item-bar-background": "rgba(1, 241, 227, 0.5)",
        "text-button-selected-currency-selector-dark-theme": "rgb(255, 255, 255)",
        "text-button-unselected-dark-theme":"rgb(71 85 105)",
        "placeholder-light": "rgba(66, 66, 134, 1)",
        "placeholder-dark": "rgba(209, 209, 209, 1)",
        "coin-page-progress-bar-outter": "#F8D2A6",
        "coin-page-progress-bar-inner": "#D4770C",
      },
      
      fontFamily: {
        'space-grotesk': ['"Space Grotesk"', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
